# Site settings
name: Daniel Aderemi
title: Daniel Aderemi | Data Analyst and Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: "https://danieladeremi.github.io"
baseurl: ''
email: dannyblast12@gmail.com
cover: "https://danieladeremi.github.io/personalsitev3/img/og.png"
logo: "https://danieladeremi.github.io/personalsitev3/img/emojis/technologist.png"
resume: "https://danieladeremi.github.io/personalsitev3/resume.pdf"

social:
  - title: email
    url: mailto:dannyblast12@gmail.com
  - title: twitter
    url: https://x.com/phantomddancer
  - title: instagram
    url: https://www.instagram.com/danieladeremi2/
  - title: github
    url: https://github.com/danieladeremi
  - title: linkedin
    url: https://www.linkedin.com/in/daniel-aderemi-4a5281244/
# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
